### ISSUE TITLE
find place name by lat-lon

### ISSUE THREAD

**Issue by bubnenkoff** [plechi/mini-geocoder#1]
Hi! Could you look at my question on SO http://stackoverflow.com/questions/42925362/can-i-use-direct-sql-queries-instead-of-using-nominatim-or-other-geo-decoders ?

Is it's possible to drop Nominatim ?

**Comment by plechi** [comment]
Hi!

Follow the instructions in the [Readme](https://github.com/plechi/mini-geocoder/blob/master/README.md) to setup a Postgres Database.

The necessary SQL Statements are in
https://github.com/plechi/mini-geocoder/blob/master/src/main/java/at/plechinger/minigeocode/repository/GeocodeRepository.java.

For example:
```sql
SELECT 
   street, 
   housenumber, 
   postcode, 
   city, 
   country, 
   longitude, 
   latitude 
FROM geocode_optimized 
WHERE full_text @@ plainto_tsquery('YOUR ADDRESS') 
```

You can optimize this query for your needs.
